name: k6 Performance Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  k6-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up k6
        run: |
          curl -sL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz | tar xz
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/

      - name: Run Load Test
        run: |
          k6 run k6_PerformanceTesting/scripts/load-test.js --out json=k6_PerformanceTesting/reports/load-result.json

      - name: Run Stress Test
        run: |
          k6 run k6_PerformanceTesting/scripts/stress-test.js --out json=k6_PerformanceTesting/reports/stress-result.json

      - name: Run Spike Test
        run: |
          k6 run k6_PerformanceTesting/scripts/spike-test.js --out json=k6_PerformanceTesting/reports/spike-result.json

      - name: Run Endurance Test
        run: |
          k6 run k6_PerformanceTesting/scripts/endurance-test.js --out json=k6_PerformanceTesting/reports/endurance-result.json

      - name: Run Advanced Login Test
        run: |
          k6 run k6_PerformanceTesting/scripts/advanced-login.js --out json=k6_PerformanceTesting/reports/advanced-login-result.json

      # Upload all JSON reports
      - name: Upload k6 JSON reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-json-reports
          path: |
            k6_PerformanceTesting/reports/*.json

      # Upload all HTML reports (generated by handleSummary in each script)
      - name: Upload k6 HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-reports
          path: |
            k6_PerformanceTesting/reports/*.html